### PR TITLE
match sentence only & add GNS parser

### PR DESCRIPTION
**Pull request by malcolmh**
I have changed the sentence matching to ignore the source device characters and also add a new parser for the GNS sentence.

### CODE REVIEW

**Comment by mpvader** [comment]
hey @malcolmh thats nice, thanks! Perhaps even the first community-originated pull request ever 👍 .

A question: in which ways did you test the change?

**Comment by malcolmh** [comment]
Therein lies a problem - I have not figured out how to build & test this. I need some guidance!

**Comment by martinbosma** [comment]
Hi @malcolmh, to build gps_dbus you need to have the SDK. You can download it [here](http://updates.victronenergy.com/feeds/venus/release/sdk). 
Note that it is based on Venus v2.15. If you are running v2.20, you need a different version. Simply replace `release` by `candidate` in the URL.
A manual how to install the SDK can be found [here](https://github.com/victronenergy/venus/wiki/howto-install-and-use-the-sdk).
Once you have installed the SDK, [setup](https://github.com/victronenergy/venus/wiki/howto-install-and-use-the-sdk#25-cross-compiling-velib-projects) the cross compiler. After that you can just type `.configure` in the `software` directory to setup the velib Makefile. Now you can use `make` to build the project.

It is also possible to build and run the project on your own machine, just skip the step where you setup the cross compiler. Perhaps you can use some GPS/GNSS emulator script to test your code.

**Comment by malcolmh** [comment]
Martin, thanks so far, but what do I need to overcome this:
./configure: 3: ./configure: ./ext/velib/mk/init_build.sh: not found

**Comment by martinbosma** [comment]
Did you also checkout the velib submodule? Use the following command: `git submodule update --init`.

**Comment by malcolmh** [comment]
From which directory?

PS: I have access rights to velib from my iMac, but not from the Debian system that I am using for venus work. I had emailed @mpvader with the public key for that machine, but as yet it cannot access velib repo.

**Comment by martinbosma** [comment]
> From which directory?

You can do this from any directory.

Regarding the key: you can generate a key on your Debian system and add this to [your GitHub account](https://github.com/settings/keys) yourself.  There is also a manual on how to generate SSH keys.

**Comment by malcolmh** [comment]
Key set up, but got this:

mherring@mini5:~/devel/dbus_gps/software$ git submodule update --init
Cloning into '/home/mherring/devel/dbus_gps/software/ext/velib'...
ssh: connect to host git.victronenergy.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@git.victronenergy.com:victron/velib.git' into submodule path '/home/mherring/devel/dbus_gps/software/ext/velib' failed
Failed to clone 'software/ext/velib'. Retry scheduled
Cloning into '/home/mherring/devel/dbus_gps/software/ext/velib'...
ssh: connect to host git.victronenergy.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@git.victronenergy.com:victron/velib.git' into submodule path '/home/mherring/devel/dbus_gps/software/ext/velib' failed
Failed to clone 'software/ext/velib' a second time, aborting

**Comment by martinbosma** [comment]
The project was still using the old URL of velib. I've updated the URL and pushed it to GitHub. You can now update your project by forking it again and re-apply your patch. Or if you are a more experienced git user, you can do a fetch and rebase from `victronenergy/dbus_gps`.
Most likely you also need to do a `git submodule sync` to synchronize with the new velb url.

**Comment by malcolmh** [comment]
Re-forked, patched and attempted submodule update, but this time repo not found:

mherring@mini5:~/devel/dbus_gps$ git submodule update --init
Submodule 'software/ext/velib' (git@github.com:victronenergy.com/velib.git) registered for path 'software/ext/velib'
Cloning into '/home/mherring/devel/dbus_gps/software/ext/velib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:victronenergy.com/velib.git' into submodule path '/home/mherring/devel/dbus_gps/software/ext/velib' failed
Failed to clone 'software/ext/velib'. Retry scheduled
Cloning into '/home/mherring/devel/dbus_gps/software/ext/velib'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:victronenergy.com/velib.git' into submodule path '/home/mherring/devel/dbus_gps/software/ext/velib' failed
Failed to clone 'software/ext/velib' a second time, aborting

**Comment by malcolmh** [comment]
Fixed: spurious ".com" in .gitmodules

**Comment by malcolmh** [comment]
now a compile error:

mherring@mini5:~/devel/dbus_gps/software$ make
Rules generated for pc-linux-arm-gnueabi-release
arm-ve-linux-gnueabi-gcc -MMD -O2 -pipe -g -feliminate-unused-debug-types -Os -Wall -Os -I/home/mherring/devel/dbus_gps/software/src/platform/pc -I/home/mherring/devel/dbus_gps/software/inc -I/home/mherring/devel/dbus_gps/software/ext/velib/inc -I/home/mherring/devel/dbus_gps/software/ext/velib/inc -I/home/mherring/devel/dbus_gps/software/ext/velib/src/plt/pc -DTARGET_pc -DRELEASE -DDBUS -I/opt/venus/rocko-arm-cortexa7hf-neon-vfpv4/sysroots/cortexa7hf-neon-vfpv4-ve-linux-gnueabi/usr/include/dbus-1.0 -I/opt/venus/rocko-arm-cortexa7hf-neon-vfpv4/sysroots/cortexa7hf-neon-vfpv4-ve-linux-gnueabi/usr/lib/dbus-1.0/include -c -o /home/mherring/devel/dbus_gps/software/ext/velib/src/base/obj/pc-linux-arm-gnueabi-release/ve_string.o /home/mherring/devel/dbus_gps/software/ext/velib/src/base/ve_string.c
In file included from /home/mherring/devel/dbus_gps/software/ext/velib/inc/velib/base/types.h:77:0,
                 from /home/mherring/devel/dbus_gps/software/ext/velib/inc/velib/base/base.h:16,
                 from /home/mherring/devel/dbus_gps/software/ext/velib/src/base/ve_string.c:1:
/opt/venus/rocko-arm-cortexa7hf-neon-vfpv4/sysroots/x86_64-ve-linux/usr/lib/arm-ve-linux-gnueabi/gcc/arm-ve-linux-gnueabi/7.3.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                ^~~~~~~~~~
compilation terminated.
Makefile:169: recipe for target '/home/mherring/devel/dbus_gps/software/ext/velib/src/base/obj/pc-linux-arm-gnueabi-release/ve_string.o' failed
make: *** [/home/mherring/devel/dbus_gps/software/ext/velib/src/base/obj/pc-linux-arm-gnueabi-release/ve_string.o] Error 1

**Comment by martinbosma** [comment]
Try to unset the `CROSS_COMPILE` variable, see [here](https://github.com/victronenergy/venus/wiki/howto-install-and-use-the-sdk#25-cross-compiling-velib-projects).

For what device are you building for? You have to use the A8 version of the SDK for the CCGX/VenuxGX and A7 for RPi, see [here](https://github.com/victronenergy/venus/wiki/howto-install-and-use-the-sdk#22-install-the-sdk).

>Fixed: spurious ".com" in .gitmodules

Correct, I missed this. Error didn't show up, because I still had the old URL checked out.

**Comment by malcolmh** [comment]
Bad link in your first "here"

I am building for RPi

**Comment by martinbosma** [comment]
Fixed the link

**Comment by malcolmh** [comment]
Unsetting CROSS_COMPILE did the trick. Successfully built & tested in RPi

**Comment by martinbosma** [comment]
@malcolmh I applied your patch in v1.03, but split it into two parts:
- Add support for multiple talker IDs
- Add support for GNS sentence

**Pull request closed without merging**
